### ISSUE TITLE
npm install fails with io.js

### ISSUE THREAD

**Issue by ralphtheninja** [mcollina/levelgraph-jsonld#25]
Depends on

- [ ] `jsonld.js` https://github.com/digitalbazaar/jsonld.js/issues/86 and
- [ ] `levelgraph` https://github.com/mcollina/levelgraph/issues/107

**Comment by ralphtheninja** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by transcranial** [comment]
No problems for me with io.js v1.6.1
