### ISSUE TITLE
Matching regular expressions in search

### ISSUE THREAD

**Issue by joel72** [mcollina/levelgraph-jsonld#30]
Hello!

Sorry for being quite a noob as i don't know whether this is possible or not and if it is possible, how it could be achieved. I tried matching regular expressions, searching for subjects of a simple levelgraph-jsonld database:

    db = levelgraphJSONLD(levelgraph('database'));

        var key = req.body.key;
        var value = req.body.value;
        
        db.search([{
            subject: db.v("id"),
            predicate: key,
            object: value
        }], function(err, results) {
            if (err) {
                console.log("ERROR");
                console.log(err);

            } else {
                res.status(200).json(results);
                db.close();
            }
        });

so basically the server receives a post request with key and value, while key and value stand for predicate and object, and returns the matching subjects. Now how can i try finding subjects that match the relation but the objects (for example) just CONTAIN a certain string? I tried querying the database with regular expressions handed over as object/value, e.g. /.*?/ /(.*?)/ or plain .*? but no results. I already read, that the filter function might be a solution for this. But aren't there any possibilities to match regular expressions or use wildcard characters in the query to avoid filtering overhead somehow? 

I hope the answer of this isn't way too easy and that i haven't just been blind looking for the answer and still that it can somehow be achieved.. 

Thanks in advance for the help!

**Comment by mcollina** [comment]
You should use filter, it's quite fast.
