### ISSUE TITLE
Question: Looking up types with search

### ISSUE THREAD

**Issue by ddibiase** [mcollina/levelgraph-jsonld#34]
Hi there,

This may seem like a pretty basic question but I'm having a heck of a time getting it to function as I expect. I have a whole graph stored with a type Blog. Here's an example node:

```
{
  '@type': 'Blog',
  '@id': 'http://www.example.com/2d4dfb70-9a2d-11e6-b4b4-21e1a79b8864'
  '@context': { '@vocab': 'http://www.example.com/' },
  wpid: '1511',
  title: 'New Speakers on the Circuit!',
  slug: 'new-speakers-on-the-circuit',
  post_excerpt: '',
  menu_order: 0,
  mime_type: '',
  parent: 0,
}
```

When I search I don't get any results:

```
this.db.search([
  {
    'predicate': 'Blog'
  }
], function(err, list) {
  console.log(list);
});
```

I suspect I'm using search incorrectly, but can't seem to muster the right syntax.

A push in the right direction would be awesome.

Thanks.

**Comment by mcollina** [comment]
I think it will have predicate http://www.w3.org/1999/02/22-rdf-syntax-ns#type and object http://www.example.com/Blog.

You can check with http://json-ld.org/playground/, and pick n-quads.

**Comment by jmatsushita** [comment]
Hey @ddibiase feel free to reopen if there's still an issue but it seems solved to me.
