### ISSUE TITLE
levelgraph peerDependencies upgrade?

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#39]
Loving levelgraph and much thanks for it! ❤️ 

Are their plans to make this work with levelgraph 1.3.1? Right now, the peerDependencies section states a dependency on 1.1.1 and if I try to depend on both levelgraph ^1.3.1 and levelgraph-jsonld ^0.5.0 here's what NPM says:

```
npm WARN peerDependencies The peer dependency levelgraph@~1.1.1 included from levelgraph-jsonld will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package levelgraph@1.3.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer levelgraph-jsonld@0.5.0 wants levelgraph@~1.1.1
```

Not sure what's changed in those two minor point releases, but thought it'd be worth noting--if nothing else for folks who may also be facing this issue.

Cheers! And keep up the greatness!! 😁

**Comment by jmatsushita** [comment]
Hi there,

There should be an update very soon which should solve this peer dependency problem.

Cheers!

**Comment by BigBlueHat** [comment]
This is out now. 😄 Great work @jmatsushita and thanks!
