### ISSUE TITLE
JSON-LD without a top-level ID don't show up in filter results

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#41]
Hit this while playing with the playground--see this commit: https://github.com/BigBlueHat/levelgraph-playground/commit/a6248a57db629a8e3d50cf60c852bca19f219f41

Essentially, without a top-level `@id` the graph didn't seem to be storing at all--despite the non-error response from `db.jsonld.put()`. Setting the `base` option fixed the issue.

Maybe defaulting `base` to `_:` as I've done on the playground is not too terribly insane? Beats the current false positive response...a bit.

Thoughts? 💭

**Comment by jmatsushita** [comment]
Hey @BigBlueHat sorry I don't get it, could you elaborate or post an example of the doc you're trying to convert and what the result is? I assume the deployed version at https://bigbluehat.github.io/levelgraph-playground/ has that `_:` hack in it so I can't see the error case? Ideal would be to submit a failing test in this repo if you feel like helping out a bit :) 

Defaulting base to `_:` is probably not a good idea if you see my musings on #42 and past discussions on #8.

**Comment by BigBlueHat** [comment]
Hrm. Honestly...I don't recall the scenario now... 😕 Guess I should've done a better job with this issue.

However, I do note that despite removing the `_:` hack that's still what's used when creating the UUID's--previously (pre-1.x) it was generating straight UUID's (no blank node prefix).

Lastly, there's some (not entirely slim) chance that I had my wires crossed between `db.put()` and `db.jsonld.put()`. It's happened...a few times. 🤷‍

Regardless, I'm closing this until the issue resurfaces in some way... Sorry about the noise!
