### ISSUE TITLE
del() empties entire storage

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#49]
So...this seems to be close to the root of the new problems.

1. Store some stuff.
2. `db.jsonld.del({}, console.log.bind(console))`
3. `db.get({}, (err, list) => console.log(list.length))` ... returns `0`

Doing the same with `db.del({}, console.log.bind(console))` doesn't empty anything--which would be the expected behavior.

I'm reading through the code now to see where I can help. Thanks!

**Comment by jmatsushita** [comment]
Yup. `db.jsonld.del({}, {preserve:true}, console.log.bind(console))` works as expected though. I think we need to Set preserve to true by default #51
