### ISSUE TITLE
Set preserve to true by default

### ISSUE THREAD

**Issue by jmatsushita** [mcollina/levelgraph-jsonld#51]
It is probably a fair expectation that data isn't deleted by default in unpredictable ways so I'd suggest we set the `preserve` option to `true` as a breaking change and allow to get the old behavior back by explicitly setting `preserve` to `false`.

This will also help with the simplicity of the conflict/overwrite API at #46 

cc @BigBlueHat

**Comment by mcollina** [comment]
Go ahead and do what you think is right. I will have little time to dedicate to this in the coming weeks.

**Comment by jmatsushita** [comment]
Ok. Last question, should we bump major version again or consider that this is part of 1.x breaking changes (given I don't think a huge amount of people depend on it)?

**Comment by mcollina** [comment]
I'd go ahead and push it as 1.0.1.
