### ISSUE TITLE
Missing information after `db.jsonld.get()`

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#56]
@jmatsushita here's a case in point from my https://github.com/BigBlueHat/page-notes/issues/9 digging...

`.put()`ing this JSON-LD...
```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno9",
  "type": "Annotation",
  "body": [
    "http://example.org/description1",
    {
      "type": "TextualBody",
      "value": "tag1"
    }
  ],
  "target": [
    "http://example.org/image1",
    "http://example.org/image2",
    {
      "source": "http://example.org/"
    }
  ]
}
```

...and then:
```js
db.jsonld.get('http://example.org/anno9', {}, (err, obj) => console.log(JSON.stringify(obj, null, '  '));
```

...gets me this...

```json
{
  "@id": "http://example.org/anno9",
  "@type": "http://www.w3.org/ns/oa#Annotation",
  "http://www.w3.org/ns/oa#hasBody": {
    "@id": "http://example.org/description1"
  },
  "http://www.w3.org/ns/oa#hasTarget": [
    {
      "@id": "http://example.org/image1"
    },
    {
      "@id": "http://example.org/image2"
    }
  ]
}
```

So. The 2 blank nodes disappeared--which is where I'm beginning to think the bug/issue is (possibly with levelgraph-jsonld).

However, on the [JSON-LD Playground](http://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fanno.jsonld%22%2C%22id%22%3A%22http%3A%2F%2Fexample.org%2Fanno9%22%2C%22type%22%3A%22Annotation%22%2C%22body%22%3A%5B%22http%3A%2F%2Fexample.org%2Fdescription1%22%2C%7B%22type%22%3A%22TextualBody%22%2C%22value%22%3A%22tag1%22%7D%5D%2C%22target%22%3A%5B%22http%3A%2F%2Fexample.org%2Fimage1%22%2C%22http%3A%2F%2Fexample.org%2Fimage2%22%2C%7B%22source%22%3A%22http%3A%2F%2Fexample.org%2F%22%7D%5D%7D&context=%7B%7D) things work as they should and I've essentially got the same JSON-LD back.

The issue is the same when passing in a `@context` (the one from the original `.put()` for simplicity):
```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "undefined": [
    "http://example.org/anno9",
    "Annotation"
  ],
  "body": "http://example.org/description1",
  "target": [
    "http://example.org/image1",
    "http://example.org/image2"
  ]
}
```

Blank nodes gone missing again...

**Comment by jmatsushita** [comment]
That's definitely a bug. I'm looking into it.

**Comment by jmatsushita** [comment]
The new 1.0.3 release should fix this! Please give it a try and let me know. Thanks a lot for reporting it!

**Comment by BigBlueHat** [comment]
Fabulous fix @jmatsushita! Much appreciated.

Playground's sporting the latest and greatest:
https://wileylabs.github.io/levelgraph-playground/
